#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export MVN=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn
export PATH=$JAVA_HOME/bin:$PATH
export MAVEN_OPTS="-Xms384m -Xmx412m"

cd $OPENSHIFT_REPO_DIR
nohup $MVN -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/.m2 -Popenshift jetty:start -Djetty.port=${OPENSHIFT_DIY_PORT} -Djetty.ip=${OPENSHIFT_DIY_IP}
