#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$JAVA_HOME/bin:$PATH
export MAVEN_OPTS="-Xms384m -Xmx412m"

cd $OPENSHIFT_REPO_DIR
nohup mvn -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/.m2 -Popenshift jetty:stop
